# Generated by Django 6.0.2 on 2026-02-08 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="URL friendly name, e.g. 'plumbing'", unique=True)),
                ('icon', models.CharField(default='🔧', help_text='Emoji or Icon class', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('township', models.CharField(choices=[('Muse', 'Muse'), ('Taunggyi', 'Taunggyi'), ('Loikaw', 'Loikaw'), ('NamKham', 'Namkham')], db_index=True, default='NamKham', help_text="e.g. 'Springfield'", max_length=100)),
                ('business_name', models.CharField(help_text='e.g. U Kyaw Electrical', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('id_type', models.CharField(choices=[('NRC', 'Pink Card'), ('SMART', 'Smart Card')], default='NRC', max_length=20)),
                ('verification_photo', models.ImageField(blank=True, null=True, upload_to='private_ids/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catergory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='providers.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
