# Generated by Django 6.0.2 on 2026-02-09 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_category_icon_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
