# Generated by Django 6.0.2 on 2026-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_providerprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='verification_photo',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verification_photo_pink_card',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verification_photo_smart_card',
            field=models.ImageField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
