# Generated by Django 6.0.2 on 2026-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('admin', 'Admin')], default='provider', max_length=10),
        ),
    ]
