# Generated by Django 6.0.2 on 2026-03-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
